 
version: '3'
services:
  backend:
    image: node:12.16.1
    container_name: backend
    hostname: OmniStack-backend
    working_dir: /backend
    ports:
        - 3333:3333
        - 3000:3000
    volumes:
        - ./backend:/backend
        - ./frontend:/frontend
    command: npm run initial
    restart: always