 
version: '3'
services:
  backend:
    image: node:12.16.1
    container_name: backend
    hostname: OmniStack
    working_dir: /app/backend
    ports:
        - 3333:3333
        # - 3000:3000
    volumes:
        - ./backend:/app/backend
        # - ./frontend:/app/frontend
    command: npm run initial
    restart: always

  frontend:
    build: 
      context: .
      dockerfile: frontend.Dockerfile
    image: frontendonmistack:latest
    container_name: frontend
    working_dir: /app/frontend
    ports: 
      - 3001:3001
      - 3002:3000
    volumes:
      - ./frontend:/app/frontend
    # command: npm start
    environment: 
      - NODE_ENV=development

  # mobile:
  #   build: 
  #     context: .
  #     dockerfile: mobile.Dockerfile
  #   image: mobileonmistack:latest
  #   container_name: mobile
  #   working_dir: /app/mobile
  #   ports:
  #       - 8081:8081
  #       - 3000:3000
  #       - 19001:19001
  #       - 19002:19002
  #       - 19006:19006
  #       - 19000:19000
  #   volumes:
  #       - ./native:/app/mobile
  #       # - ./native/node_modules:/app/mobile/node_modules